// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paxos.proto

/*
Package protos is a generated protocol buffer package.

*
the scene is from lamport-paxos, The single-Decree Synod
and I change some details.
see more http://lamport.azurewebsites.net/pubs/lamport-paxos.pdf

It is generated from these files:
	paxos.proto

It has these top-level messages:
	NextBallot
	LastVote
	BeginBallot
	Voted
	Success
	Leger
	Empty
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NextBallot struct {
	Id     uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Priest uint32 `protobuf:"varint,2,opt,name=priest" json:"priest,omitempty"`
}

func (m *NextBallot) Reset()                    { *m = NextBallot{} }
func (m *NextBallot) String() string            { return proto.CompactTextString(m) }
func (*NextBallot) ProtoMessage()               {}
func (*NextBallot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NextBallot) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NextBallot) GetPriest() uint32 {
	if m != nil {
		return m.Priest
	}
	return 0
}

type LastVote struct {
	Id     uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	MaxId  uint32 `protobuf:"varint,2,opt,name=maxId" json:"maxId,omitempty"`
	Priest uint32 `protobuf:"varint,3,opt,name=priest" json:"priest,omitempty"`
}

func (m *LastVote) Reset()                    { *m = LastVote{} }
func (m *LastVote) String() string            { return proto.CompactTextString(m) }
func (*LastVote) ProtoMessage()               {}
func (*LastVote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LastVote) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LastVote) GetMaxId() uint32 {
	if m != nil {
		return m.MaxId
	}
	return 0
}

func (m *LastVote) GetPriest() uint32 {
	if m != nil {
		return m.Priest
	}
	return 0
}

type BeginBallot struct {
	Id     uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Decree string `protobuf:"bytes,2,opt,name=decree" json:"decree,omitempty"`
	Priest uint32 `protobuf:"varint,3,opt,name=priest" json:"priest,omitempty"`
}

func (m *BeginBallot) Reset()                    { *m = BeginBallot{} }
func (m *BeginBallot) String() string            { return proto.CompactTextString(m) }
func (*BeginBallot) ProtoMessage()               {}
func (*BeginBallot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BeginBallot) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BeginBallot) GetDecree() string {
	if m != nil {
		return m.Decree
	}
	return ""
}

func (m *BeginBallot) GetPriest() uint32 {
	if m != nil {
		return m.Priest
	}
	return 0
}

type Voted struct {
	Vote   bool   `protobuf:"varint,1,opt,name=vote" json:"vote,omitempty"`
	Id     uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Priest uint32 `protobuf:"varint,3,opt,name=priest" json:"priest,omitempty"`
}

func (m *Voted) Reset()                    { *m = Voted{} }
func (m *Voted) String() string            { return proto.CompactTextString(m) }
func (*Voted) ProtoMessage()               {}
func (*Voted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Voted) GetVote() bool {
	if m != nil {
		return m.Vote
	}
	return false
}

func (m *Voted) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Voted) GetPriest() uint32 {
	if m != nil {
		return m.Priest
	}
	return 0
}

type Success struct {
	Id     uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Decree string `protobuf:"bytes,2,opt,name=decree" json:"decree,omitempty"`
	Priest uint32 `protobuf:"varint,3,opt,name=priest" json:"priest,omitempty"`
}

func (m *Success) Reset()                    { *m = Success{} }
func (m *Success) String() string            { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()               {}
func (*Success) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Success) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Success) GetDecree() string {
	if m != nil {
		return m.Decree
	}
	return ""
}

func (m *Success) GetPriest() uint32 {
	if m != nil {
		return m.Priest
	}
	return 0
}

type Leger struct {
	Values map[uint32]string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Leger) Reset()                    { *m = Leger{} }
func (m *Leger) String() string            { return proto.CompactTextString(m) }
func (*Leger) ProtoMessage()               {}
func (*Leger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Leger) GetValues() map[uint32]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*NextBallot)(nil), "protos.NextBallot")
	proto.RegisterType((*LastVote)(nil), "protos.LastVote")
	proto.RegisterType((*BeginBallot)(nil), "protos.BeginBallot")
	proto.RegisterType((*Voted)(nil), "protos.Voted")
	proto.RegisterType((*Success)(nil), "protos.Success")
	proto.RegisterType((*Leger)(nil), "protos.Leger")
	proto.RegisterType((*Empty)(nil), "protos.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Paxos service

type PaxosClient interface {
	DealPreBallot(ctx context.Context, in *NextBallot, opts ...grpc.CallOption) (*LastVote, error)
	DealBallot(ctx context.Context, in *BeginBallot, opts ...grpc.CallOption) (*Voted, error)
	RecordDecree(ctx context.Context, in *Success, opts ...grpc.CallOption) (*Empty, error)
	Synchronize(ctx context.Context, in *Leger, opts ...grpc.CallOption) (*Leger, error)
}

type paxosClient struct {
	cc *grpc.ClientConn
}

func NewPaxosClient(cc *grpc.ClientConn) PaxosClient {
	return &paxosClient{cc}
}

func (c *paxosClient) DealPreBallot(ctx context.Context, in *NextBallot, opts ...grpc.CallOption) (*LastVote, error) {
	out := new(LastVote)
	err := grpc.Invoke(ctx, "/protos.Paxos/DealPreBallot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) DealBallot(ctx context.Context, in *BeginBallot, opts ...grpc.CallOption) (*Voted, error) {
	out := new(Voted)
	err := grpc.Invoke(ctx, "/protos.Paxos/DealBallot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) RecordDecree(ctx context.Context, in *Success, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/protos.Paxos/RecordDecree", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) Synchronize(ctx context.Context, in *Leger, opts ...grpc.CallOption) (*Leger, error) {
	out := new(Leger)
	err := grpc.Invoke(ctx, "/protos.Paxos/Synchronize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Paxos service

type PaxosServer interface {
	DealPreBallot(context.Context, *NextBallot) (*LastVote, error)
	DealBallot(context.Context, *BeginBallot) (*Voted, error)
	RecordDecree(context.Context, *Success) (*Empty, error)
	Synchronize(context.Context, *Leger) (*Leger, error)
}

func RegisterPaxosServer(s *grpc.Server, srv PaxosServer) {
	s.RegisterService(&_Paxos_serviceDesc, srv)
}

func _Paxos_DealPreBallot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextBallot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).DealPreBallot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Paxos/DealPreBallot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).DealPreBallot(ctx, req.(*NextBallot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_DealBallot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginBallot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).DealBallot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Paxos/DealBallot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).DealBallot(ctx, req.(*BeginBallot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_RecordDecree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Success)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).RecordDecree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Paxos/RecordDecree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).RecordDecree(ctx, req.(*Success))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_Synchronize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Leger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Synchronize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Paxos/Synchronize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Synchronize(ctx, req.(*Leger))
	}
	return interceptor(ctx, in, info, handler)
}

var _Paxos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Paxos",
	HandlerType: (*PaxosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DealPreBallot",
			Handler:    _Paxos_DealPreBallot_Handler,
		},
		{
			MethodName: "DealBallot",
			Handler:    _Paxos_DealBallot_Handler,
		},
		{
			MethodName: "RecordDecree",
			Handler:    _Paxos_RecordDecree_Handler,
		},
		{
			MethodName: "Synchronize",
			Handler:    _Paxos_Synchronize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}

func init() { proto.RegisterFile("paxos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x14, 0x6c, 0x8b, 0x05, 0x7c, 0xb5, 0x4a, 0x56, 0x63, 0xb0, 0x27, 0xd2, 0x13, 0x17, 0x89, 0xa2,
	0x89, 0x1f, 0x47, 0x84, 0x44, 0x12, 0x34, 0xa4, 0x24, 0xdc, 0x6b, 0xfb, 0x82, 0x8d, 0xa5, 0xdb,
	0xec, 0x2e, 0x84, 0xfa, 0x3f, 0xfd, 0x3f, 0xa6, 0xdb, 0xad, 0xd0, 0x28, 0x27, 0x4f, 0xdd, 0x79,
	0xfb, 0x66, 0x32, 0x9d, 0x59, 0xb0, 0x52, 0x7f, 0x43, 0x79, 0x2f, 0x65, 0x54, 0x50, 0x52, 0x97,
	0x1f, 0xee, 0xde, 0x02, 0xbc, 0xe2, 0x46, 0x0c, 0xfc, 0x38, 0xa6, 0x82, 0x1c, 0x83, 0x11, 0x85,
	0x6d, 0xbd, 0xa3, 0x77, 0x6d, 0xcf, 0x88, 0x42, 0x72, 0x0e, 0xf5, 0x94, 0x45, 0xc8, 0x45, 0xdb,
	0x90, 0x33, 0x85, 0xdc, 0x67, 0x68, 0x4e, 0x7c, 0x2e, 0xe6, 0x54, 0xe0, 0x2f, 0xce, 0x19, 0x98,
	0x4b, 0x7f, 0x33, 0x0e, 0x15, 0xa5, 0x00, 0x3b, 0x4a, 0xb5, 0x8a, 0xd2, 0x0b, 0x58, 0x03, 0x5c,
	0x44, 0xc9, 0x7e, 0x03, 0x21, 0x06, 0x0c, 0x51, 0xaa, 0x1d, 0x7a, 0x0a, 0xed, 0x95, 0x7b, 0x02,
	0x33, 0x37, 0x15, 0x12, 0x02, 0x07, 0x6b, 0x2a, 0x50, 0x4a, 0x35, 0x3d, 0x79, 0x56, 0xe2, 0xc6,
	0x1f, 0x7f, 0x57, 0x15, 0x19, 0x43, 0x63, 0xb6, 0x0a, 0x02, 0xe4, 0xfc, 0xdf, 0x7e, 0x56, 0x60,
	0x4e, 0x70, 0x81, 0x8c, 0x5c, 0x43, 0x7d, 0xed, 0xc7, 0x2b, 0xe4, 0x6d, 0xbd, 0x53, 0xeb, 0x5a,
	0xfd, 0x8b, 0xa2, 0x07, 0xde, 0x93, 0xd7, 0xbd, 0xb9, 0xbc, 0x1b, 0x25, 0x82, 0x65, 0x9e, 0x5a,
	0x74, 0x1e, 0xc0, 0xda, 0x19, 0x93, 0x16, 0xd4, 0x3e, 0x30, 0x53, 0x5e, 0xf2, 0x63, 0x9e, 0xb4,
	0x5c, 0x55, 0x5e, 0x0a, 0xf0, 0x68, 0xdc, 0xeb, 0x6e, 0x03, 0xcc, 0xd1, 0x32, 0x15, 0x59, 0xff,
	0x4b, 0x07, 0x73, 0x9a, 0xd7, 0x4e, 0xee, 0xc0, 0x1e, 0xa2, 0x1f, 0x4f, 0x19, 0xaa, 0xa8, 0x49,
	0xe9, 0x60, 0xdb, 0xbf, 0xd3, 0xfa, 0x71, 0xa5, 0xda, 0x75, 0x35, 0xd2, 0x07, 0xc8, 0x89, 0x8a,
	0x75, 0x5a, 0x6e, 0xec, 0xb4, 0xe6, 0xd8, 0xe5, 0x50, 0x66, 0xef, 0x6a, 0xe4, 0x0a, 0x8e, 0x3c,
	0x0c, 0x28, 0x0b, 0x87, 0x45, 0x3c, 0x27, 0xe5, 0x82, 0xca, 0x75, 0xcb, 0x90, 0x36, 0x5d, 0x8d,
	0x5c, 0x82, 0x35, 0xcb, 0x92, 0xe0, 0x9d, 0xd1, 0x24, 0xfa, 0x44, 0x62, 0x57, 0xe2, 0x71, 0xaa,
	0xd0, 0xd5, 0xde, 0x8a, 0xe7, 0x7b, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x79, 0xd4, 0x31, 0x58,
	0xd4, 0x02, 0x00, 0x00,
}
